args: Namespace(batch_size=16, checkpoint=None, model='pointMLPElite', msg='20240415124215-4332', num_classes=40, num_points=1024, partition='generated')
==> Using device: cuda
==> Preparing data..
(3, 2048, 3)
(96, 1)
3
==> Building model..
==> RESULTS:
libibverbs: Warning: couldn't load driver 'libmlx4-rdmav34.so': libmlx4-rdmav34.so: cannot open shared object file: No such file or directory
(b'chair_ball.stl', b'chair_outside.stl', b'chair_poisson.stl') :
	True: [8 8 8]
	Pred: [26 26 26]
 [>................................................................]  Step: 6s662ms | Tot: 0ms | Loss: 3.444 | Acc: 0.000% (0/3) 1/1 
/home/johnstonem/.conda/envs/pointmlp/lib/python3.8/site-packages/sklearn/metrics/_classification.py:2399: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")

Vanilla out: {'loss': 3.444, 'acc': 0.0, 'acc_avg': 0.0, 'time': 3}
